[project]
name = "notification-service"
version = "1.0.0"
description = "Microservice handling searches (interface with elastic, metadata, subscription)"
authors = []
requires-python = ">=3.12"


dependencies = [
    "aiosmtplib==4.0.0",
]
